--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyShopUI
branches:
  - master
  - pmmp-4.0.0
projects:
  PiggyShopUI:
    path: ""
    libs:
      - src: DaPigGuy/FormAPI-4.0.0/libFormAPI
        version: ^2.1.0
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.0
    lint:
      phpstan: false
...
