--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyShopUI
branches:
  - master
projects:
  PiggyShopUI:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: ParoxityTeam/Commando/Commando
        version: ^2.1.0
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^2.0.0
    lint:
      phpstan: false
...