--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyShopUI
branches:
  - master
projects:
  PiggyShopUI:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: Paroxity/Commando/Commando
        version: ^3.1.0
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.2
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint:
      phpstan: false
...
