name: PiggyShopUI
main: DaPigGuy\PiggyShopUI\PiggyShopUI
version: 2.1.1
api: 4.0.0
load: POSTWORLD
author: DaPigGuy
softdepend: ["EconomyAPI", "MultiEconomy"]
website: "https://github.com/DaPigGuy/PiggyShopUI/"

permissions:
  piggyshopui:
    default: false
    description: "Allows usage of all PiggyShopUI features"
  piggyshopui.command:
    default: op
    description: "Allow usage of all PiggyShopUI commands"
  piggyshopui.command.shop:
    default: op
    description: "Allow usage of the /shop commands"
  piggyshopui.command.shop.edit:
    default: op
    description: "Allow usage of the /shop edit subcommand"
  piggyshopui.command.shop.use:
    default: true
    description: "Allow usage of the /shop command" 
  piggyshopui.category.:
    default: true
    description: "use categorys?"
