name: PiggyShopUI
main: DaPigGuy\PiggyShopUI\PiggyShopUI
version: 2.0.4
api: 3.2.0
load: POSTWORLD
author: DaPigGuy
softdepend: ["EconomyAPI", "MultiEconomy"]
website: "https://github.com/DaPigGuy/PiggyShopUI/"
permissions:
  piggyshopui:
    default: false
    description: "Allows usage of all PiggyShopUI features"
    children:
      piggyshopui.command:
        default: op
        description: "Allow usage of all PiggyShopUI commands"
        children:
          piggyshopui.command.shop:
            default: op
            description: "Allow usage of the /shop commands"
            children:
              piggyshopui.command.shop.edit:
                default: op
                description: "Allow usage of the /shop edit subcommand"
              piggyshopui.command.shop.use:
                default: true
                description: "Allow usage of the /shop command"