name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: mkdir vendor
      - name: Download Virion Dependencies
        run: |
          wget -O vendor/FormAPI.phar https://poggit.pmmp.io/r/77082/FormAPI_dev-1.phar
          wget -O vendor/libPiggyEconomy.phar https://poggit.pmmp.io/r/163250/libPiggyEconomy_dev-12.phar
          wget -O vendor/Commando.phar https://poggit.pmmp.io/r/94451/Commando_dev-3.phar
      - name: Run PHPStan
        uses: paroxity/pmmp-phpstan-action@4.2.0
        with:
          phpstan-config: phpstan.neon.dist